site_name: C4C Dev Docs
repo_url: https://github.com/Code-4-Community/c4c-dev-docs

theme:
  name: material
  favicon: "img/favicon.ico"
  features:
    - tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - MkDocs: mkdocs-starter.md
  - Lucy's Love Bus:
    - Home: llb/index.md
    - llb/llb-api-spec.md
    - llb/llb-auth-api.md
  - Speak for the Trees:
    - Home: sftt/index.md
    - sftt/sftt-api-spec.md
    - sftt/sftt-auth-api.md
  - API Spec Example: api-spec-example.md
