site_name: Code4Community Documentation
repo_url: https://github.com/Code-4-Community/c4c-dev-docs
repo_name: c4c-dev-docs
edit_uri: ""

theme:
    name: material
    custom_dir: docs/overrides
    favicon: img/favicon.ico
    features:
        - tabs
        - navigation.tabs
    palette:
        - scheme: default
          toggle:
            icon: material/lightbulb-outline
            name: Switch to dark mode
          primary: indigo
          accent: pink
        - scheme: slate
          toggle:
            icon: material/lightbulb
            name: Switch to light mode
          primary: indigo
          accent: pink

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
            linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
            toc_depth: 3

nav:
    - Home: index.md
    - The Organization:
        - Home: organization/index.md
        - Constitution: organization/constitution.md
        - Social Contract: organization/social_contract.md
        - Structure:
            - E-Board: organization/structure/e-board.md
            - Product Teams: organization/structure/product-teams.md
        - Recruitment:
            - Philosophy: organization/recruitment/philosophy.md
            - Onboarding: organization/recruitment/onboarding.md
            - Offboarding: organization/recruitment/offboarding.md
    - Getting Started:
        - Home: getting-started/index.md
        - Product Workflow: getting-started/product-workflow.md
        - Codebase Setup Guide: getting-started/setup-local-dev.md
        - Contributing to Dev Docs: getting-started/mkdocs-starter.md
        - API Specification Example: getting-started/api-spec-example.md
        - Add Yourself to People page: getting-started/people.md
        - Working on a ticket: getting-started/ticket.md
    - Guides + Resources:
        - Home: guides/index.md
        - Jumpstart Fullstack Course: https://learn.c4cneu.com
        - Frontend Data Architecture with Redux: guides/frontend-redux.md
        - Scaffold Repositories: guides/scaffold-repos.md
        - How To Build Your Own Website: guides/website-tutorial.md
    - Dev Ops:
        - Home: dev-ops/index.md
        - Backend Deployment: dev-ops/aws/backend-deployment.md
    - LLB:
        - Home: llb/index.md
        - Feature API Specification: llb/llb-api-spec.md
        - Auth API Specification: llb/llb-auth-api.md
        - Local Image Upload Guide: llb/llb-local-image-upload.md
        - Testing Specification: llb/llb-test-spec.md
        - How to style AntD components with styled-components: llb/antd-styled-components.md
    - SFTT:
        - Home: sftt/index.md
        - API Specification: sftt/sftt-api-spec.md
        - ArcGIS Architecture: sftt/arcgis-architecture.md
        - Frontend Guides:
            - Walkthrough: sftt/frontend-guides/sftt-frontend-walkthrough.md
            - Routing: sftt/frontend-guides/sftt-routing.md
    - HATS:
        - Home: hats/index.md
        - Auth API Specification: hats/api-spec-auth.md
        - Countries API Specification: hats/api-spec-country.md
        - Schools API Specification: hats/api-spec-school.md
        - School Contacts API Specification: hats/api-spec-school-contact.md
        - Reports API Specification: hats/api-spec-school-report.md
        - Books API Specification: hats/api-spec-school-books.md
    - JPAL:
        - Home: jpal/index.md
    - LBFE:
        - Home: lbfe/index.md
