site_name: C4C Dev Docs

nav:
  - Home: index.md
  - MkDocs: mkdocs-starter.md
  - SFTT Feature API: sftt-api-spec.md
  - SFTT Auth API: sftt-auth-api.md
  - LLB Feature API: llb-api-spec.md
  - LLB Auth API: llb-auth-api.md

theme:
  name: material