site_name: Code4Community Documentation
repo_url: https://github.com/Code-4-Community/c4c-dev-docs

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - tabs
  palette:
    primary: deep purple

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3

nav:
  - Home: index.md
  - Getting Started:
      - Home: getting-started/index.md
      - Product Workflow: getting-started/product-workflow.md
      - Codebase Setup Guide: getting-started/setup-local-dev.md
      - Contributing to Dev Docs: getting-started/mkdocs-starter.md
      - API Specification Example: getting-started/api-spec-example.md
  - Guides + Resources:
      - Home: guides/index.md
      - Jumpstart Fullstack Course: https://learn.c4cneu.com
      - Frontend Data Architecture with Redux: guides/frontend-redux.md
      - Scaffold Repositories: guides/scaffold-repos.md
  - Lucy's Love Bus (LLB):
      - Home: llb/index.md
      - Feature API Specification: llb/llb-api-spec.md
      - Auth API Specification: llb/llb-auth-api.md
      - Local Image Upload Guide: llb/llb-local-image-upload.md
      - Testing Specification: llb/llb-test-spec.md
      - How to style AntD components with styled-components: llb/antd-styled-components.md
  - Speak for the Trees (SFTT):
      - Home: sftt/index.md
      - API Specification: sftt/sftt-api-spec.md
      - ArcGIS Architecture: sftt/arcgis-architecture.md
  - Hands Across the Sea (HATS):
      - Home: hats/index.md
      - Auth API Specification: hats/api-spec-auth.md
      - Countries API Specification: hats/api-spec-country.md
      - Schools API Specification: hats/api-spec-school.md
      - School Contacts API Specification: hats/api-spec-school-contact.md
      - Reports API Specification: hats/api-spec-school-report.md
      - Books API Specification: hats/api-spec-school-books.md
  - C4C Website:
      - Add Yourself to People page: c4cwebsite/people.md
  - Amazon Web Services:
      - Backend Deployment: aws/backend-deployment.md
