site_name: Code4Community Documentation
repo_url: https://github.com/Code-4-Community/c4c-dev-docs

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
      - Home: getting-started/index.md
      - Product Workflow: getting-started/product-workflow.md
      - Codebase Setup Guide: getting-started/setup-local-dev.md
      - Contributing to Dev Docs: getting-started/mkdocs-starter.md
      - API Specification Example: getting-started/api-spec-example.md
  - Lucy's Love Bus (LLB):
      - Home: llb/index.md
      - Feature API Specification: llb/llb-api-spec.md
      - Auth API Specification: llb/llb-auth-api.md
  - Speak for the Trees (SFTT):
      - Home: sftt/index.md
      - Map Architecture: sftt/map-architecture.md
      - Feature API Specification: sftt/sftt-api-spec.md
      - Auth API Specification: sftt/sftt-auth-api.md
  - Hands Across the Sea (HATS):
      - Home: hats/index.md
      - Auth API Specification: hats/api-spec-auth.md
      - Countries API Specification: hats/api-spec-country.md
      - Schools API Specification: hats/api-spec-school.md
  - C4C Website:
      - Add Yourself to People page: c4cwebsite/people.md
  - Amazon Web Services:
      - Backend Deployment: aws/backend-deployment.md
